/**
 * Spaceships, one table at a time.
 *
 * This is RULES.md as code, and it is deliberately a mirror of `ml/engine.py`
 * rather than a fresh reading of the rules: the trained opponent in
 * `policies.ts` was fitted against that engine's numbers, so any drift between
 * the two would quietly hand it a different game to the one it learned. The
 * test suite pins the pair together -- `tests/fixtures/positions.json` is
 * generated by the Python engine and replayed against this one.
 *
 * The differences from the batched engine are presentational, not mechanical.
 * There the deck is a vector of thirteen counts, because that is what
 * vectorises; here it is a shuffled list of cards, because a table has a deck
 * on it and the discard pile shows its top card. Drawing from either is the
 * same distribution.
 *
 * The clauses that carry the game, stated plainly:
 *
 *   - A shield absorbs its value on every attack and is never consumed. It
 *     changes only when somebody spends a turn swapping it -- yours or theirs.
 *   - A charge attack is all or nothing, and the declaration is binding: the
 *     bank is spent whether it breaks through or bounces off.
 *   - Any breakthrough destroys the defender's whole bank, declared or not.
 *     Equal counts as breaking through.
 *   - Charges are face down to everybody, their owner included.
 *   - When the deck runs out the discards are reshuffled. With nothing in
 *     either pile you must fire your bank with no drawn card, or pass.
 */

export const RANKS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13] as const;
export const MEAN_CARD = 7;

/** Action indices, in the order the trained network's output layer expects. */
export const CHARGE = 0;
export const SWAP_SELF = 1;
export const ATTACK = 2;
export const CHARGE_ATTACK = 3;
export const SWAP_TARGET = 4;
export const N_ACTIONS = 5;

export type Action =
  | typeof CHARGE
  | typeof SWAP_SELF
  | typeof ATTACK
  | typeof CHARGE_ATTACK
  | typeof SWAP_TARGET;

export const ACTION_NAMES = [
  "charge",
  "swap own shield",
  "attack",
  "charge attack",
  "swap their shield",
] as const;

export interface Ship {
  name: string;
  human: boolean;
  /** The three dealt cards, kept face up as a record of where you started. */
  healthCards: number[];
  startHealth: number;
  /** The number on the paper. Allowed to go negative, exactly as it does in
   *  the Python engine; the display clamps it, the arithmetic does not. */
  health: number;
  shield: number;
  /** Face-down ranks. Nothing outside resolution may read these values. */
  bank: number[];
  out: boolean;
  /** Every total this ship has written down, in order. */
  history: number[];
}

export interface Game {
  seats: number;
  ships: Ship[];
  deck: number[];
  discard: number[];
  current: number;
  turns: number;
  reshuffles: number;
  over: boolean;
  seed: number;
  /** Advances with the deck; kept in the state so a game is serialisable. */
  rngState: number;
}

/* --------------------------------------------------------------- the deck */

export type Rng = () => number;

/** mulberry32: small, fast, and seedable, so a deal can be replayed. */
export function makeRng(seed: number): Rng {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** The rng lives in the game state, so drawing has to thread it through. */
function rngFor(g: Game): { next: Rng; commit: () => void } {
  const rng = makeRng(g.rngState);
  let calls = 0;
  return {
    next: () => {
      calls += 1;
      return rng();
    },
    // Re-seed from the number of draws taken, so the stream never repeats.
    commit: () => {
      g.rngState = (g.rngState + calls * 0x9e3779b1) >>> 0;
    },
  };
}

function shuffle<T>(xs: T[], rng: Rng): T[] {
  const a = xs.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function freshDeck(rng: Rng): number[] {
  const d: number[] = [];
  for (const v of RANKS) for (let s = 0; s < 4; s++) d.push(v);
  return shuffle(d, rng);
}

/** Counts by rank, which is the only view of a pile anyone is entitled to. */
export function countsOf(cards: number[]): number[] {
  const c = new Array(13).fill(0);
  for (const v of cards) c[v - 1] += 1;
  return c;
}

/* ------------------------------------------------------------------ dealing */

export interface DealOptions {
  seats: number;
  names: string[];
  /** Which seat the human takes. The rest are engines. */
  humanSeat: number;
  seed?: number;
}

export function deal(opts: DealOptions): Game {
  const seed = (opts.seed ?? Math.floor(Math.random() * 0xffffffff)) >>> 0;
  const rng = makeRng(seed);
  const deck = freshDeck(rng);

  const ships: Ship[] = [];
  for (let i = 0; i < opts.seats; i++) {
    const healthCards = [deck.pop()!, deck.pop()!, deck.pop()!];
    const total = healthCards.reduce((a, b) => a + b, 0);
    ships.push({
      name: opts.names[i] ?? `Seat ${i + 1}`,
      human: i === opts.humanSeat,
      healthCards,
      startHealth: total,
      health: total,
      shield: deck.pop()!,
      bank: [],
      out: false,
      history: [total],
    });
  }

  // Lowest starting health opens -- the handicap you can never repair. Ties
  // go to the lowest shield, and a tie there is settled by a deal.
  let first = 0;
  for (let i = 1; i < ships.length; i++) {
    const a = ships[i];
    const b = ships[first];
    if (
      a.startHealth < b.startHealth ||
      (a.startHealth === b.startHealth && a.shield < b.shield)
    ) {
      first = i;
    }
  }

  return {
    seats: opts.seats,
    ships,
    deck,
    discard: [],
    current: first,
    turns: 0,
    reshuffles: 0,
    over: false,
    seed,
    // Past the deal, so replaying a seed gives the same opening position.
    rngState: (seed + 0x1234567) >>> 0,
  };
}

export function clone(g: Game): Game {
  return {
    ...g,
    deck: g.deck.slice(),
    discard: g.discard.slice(),
    ships: g.ships.map((s) => ({
      ...s,
      healthCards: s.healthCards.slice(),
      bank: s.bank.slice(),
      history: s.history.slice(),
    })),
  };
}

/* ------------------------------------------------------------------- views */

export const livingSeats = (g: Game): number[] =>
  g.ships.map((s, i) => (s.out ? -1 : i)).filter((i) => i >= 0);

export const canDraw = (g: Game): boolean =>
  g.deck.length + g.discard.length > 0;

/**
 * Whom the engine points at.
 *
 * Not a learned choice, and deliberately so: above two players an action space
 * indexed by seat is not permutation-invariant, so a learned head over seats
 * would mostly be learning which chair it sat in. The rule is the one the
 * analysis scripts use -- softest shield first, and among equal shields the
 * one sitting on the biggest bank, which is the disarm shot the design notes
 * say the game depends on somebody taking.
 */
export function chooseTarget(g: Game, mover: number): number {
  let best = -1;
  let bestKey = Infinity;
  for (let i = 0; i < g.seats; i++) {
    if (i === mover || g.ships[i].out) continue;
    const s = g.ships[i];
    const key = s.shield * 100000 - Math.min(s.bank.length, 20) * 1000 + s.health;
    if (key < bestKey) {
      bestKey = key;
      best = i;
    }
  }
  return best < 0 ? mover : best;
}

/**
 * [5] mask. An all-false row must pass: nothing to draw and no bank to fire,
 * which is the one dead end the rules allow.
 */
export function legalActions(g: Game, mover: number, target: number): boolean[] {
  const draw = canDraw(g);
  const banked = g.ships[mover].bank.length > 0;
  const hasTarget = target !== mover && !g.ships[target].out;
  const legal = new Array(N_ACTIONS).fill(false);
  legal[CHARGE] = draw;
  legal[SWAP_SELF] = draw;
  legal[ATTACK] = draw && hasTarget;
  // A charge attack with an empty bank is just a plain attack, so it is not
  // offered. With no card to draw it is the only thing offered.
  legal[CHARGE_ATTACK] = banked && hasTarget;
  legal[SWAP_TARGET] = draw && hasTarget;
  return legal;
}

/* ------------------------------------------------------------------ events */

export type GameEvent =
  | { kind: "charge"; actor: number; count: number; reshuffled: boolean }
  | {
      kind: "swap";
      actor: number;
      subject: number;
      from: number;
      to: number;
      reshuffled: boolean;
    }
  | {
      kind: "attack";
      actor: number;
      target: number;
      declared: boolean;
      drawn: number | null;
      bank: number[];
      total: number;
      shield: number;
      broke: boolean;
      damage: number;
      disarmed: number;
      killed: boolean;
      keptBank: number;
      reshuffled: boolean;
    }
  | { kind: "pass"; actor: number }
  | { kind: "illegal"; actor: number };

/* -------------------------------------------------------------- resolution */

function drawCard(g: Game, note: { reshuffled: boolean }): number | null {
  if (g.deck.length === 0) {
    if (g.discard.length === 0) return null;
    const { next, commit } = rngFor(g);
    g.deck = shuffle(g.discard, next);
    commit();
    g.discard = [];
    g.reshuffles += 1;
    note.reshuffled = true;
  }
  return g.deck.pop()!;
}

/**
 * Apply one action and hand the turn on. Returns a fresh state -- the caller's
 * copy is never touched -- along with what happened, in enough detail for the
 * table to narrate it.
 *
 * An illegal action is reported rather than quietly rewritten, so a bug shows
 * up as a stalled turn instead of as silent cheating.
 */
export function applyAction(
  game: Game,
  action: Action | -1,
  target: number,
): { game: Game; event: GameEvent } {
  const g = clone(game);
  const mover = g.current;
  const me = g.ships[mover];
  const note = { reshuffled: false };

  if (action === -1 || !legalActions(g, mover, target)[action]) {
    const event: GameEvent =
      action === -1
        ? { kind: "pass", actor: mover }
        : { kind: "illegal", actor: mover };
    advance(g);
    return { game: g, event };
  }

  let event: GameEvent;

  if (action === CHARGE) {
    const card = drawCard(g, note)!;
    me.bank.push(card);
    event = {
      kind: "charge",
      actor: mover,
      count: me.bank.length,
      reshuffled: note.reshuffled,
    };
  } else if (action === SWAP_SELF || action === SWAP_TARGET) {
    const subject = action === SWAP_SELF ? mover : target;
    const s = g.ships[subject];
    const from = s.shield;
    // The old shield is discarded and the new one comes off the deck blind:
    // you are stuck with whatever it is, better or worse.
    g.discard.push(from);
    s.shield = drawCard(g, note)!;
    event = {
      kind: "swap",
      actor: mover,
      subject,
      from,
      to: s.shield,
      reshuffled: note.reshuffled,
    };
  } else {
    const declared = action === CHARGE_ATTACK;
    const foe = g.ships[target];
    const bank = declared ? me.bank.slice() : [];
    const drawn = canDraw(g) ? drawCard(g, note) : null;
    const total =
      (drawn ?? 0) + (declared ? bank.reduce((a, b) => a + b, 0) : 0);
    const shield = foe.shield;
    const broke = total >= shield;
    const damage = broke ? total - shield : 0;
    const disarmed = broke ? foe.bank.length : 0;

    if (broke) {
      // Any breakthrough destroys the defender's whole bank, declared or not.
      if (foe.bank.length) g.discard.push(...foe.bank.splice(0));
      foe.health -= damage;
      if (damage > 0) foe.history.push(Math.max(0, foe.health));
    }
    if (drawn !== null) g.discard.push(drawn);
    if (declared) {
      g.discard.push(...me.bank.splice(0));
    }

    const killed = foe.health <= 0 && !foe.out;
    event = {
      kind: "attack",
      actor: mover,
      target,
      declared,
      drawn,
      bank,
      total,
      shield,
      broke,
      damage,
      disarmed,
      killed,
      keptBank: me.bank.length,
      reshuffled: note.reshuffled,
    };
  }

  resolveDeaths(g);
  advance(g);
  return { game: g, event };
}

function resolveDeaths(g: Game) {
  for (const s of g.ships) {
    if (s.out || s.health > 0) continue;
    // A destroyed ship's shield and live bank fall back into circulation. Its
    // health cards do not, same as everybody's. (RULES.md is silent on this;
    // the Python engine decided it the same way.)
    s.out = true;
    if (s.shield > 0) g.discard.push(s.shield);
    if (s.bank.length) g.discard.push(...s.bank.splice(0));
    s.shield = 0;
  }
}

function advance(g: Game) {
  g.turns += 1;
  let next = (g.current + 1) % g.seats;
  for (let k = 0; k < g.seats && g.ships[next].out; k++) {
    next = (next + 1) % g.seats;
  }
  g.current = next;
  g.over = livingSeats(g).length <= 1;
}

export function winner(g: Game): number {
  const live = livingSeats(g);
  return live.length === 1 ? live[0] : -1;
}
