"""Hand the trained ship over to the browser.

The web app in ``src/`` plays the same game as ``ml/engine.py`` and is faced by
the same policies, but it is a TypeScript port and a port is only worth as much
as its evidence. This script produces both halves of that evidence:

    python3 -m ml.export_web

  1. ``src/game/policy.ts`` -- the trained weights, plus the feature order and
     action order they were trained against, so the port cannot silently
     reindex them. A module rather than a JSON file, so the bundler and the
     test runner load it exactly the same way.
  2. ``tests/fixtures/positions.json`` -- a few hundred positions taken from
     real self-play, each with the features, the network's scores and every
     policy's chosen action as this engine computes them. The JS test suite
     replays them and demands the same numbers.

Retrain and re-run this and the browser opponent moves with it.
"""

from __future__ import annotations

import json
import os

import numpy as np

from .engine import (ACTION_NAMES, FEATURE_NAMES, Spaceships, N_ACTIONS)
from .policies import GreedyPolicy, HeuristicPolicy, MLPPolicy

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHECKPOINT = os.path.join(ROOT, "ml", "runs", "duel.json")
POLICY_OUT = os.path.join(ROOT, "src", "game", "policy.ts")
FIXTURE_OUT = os.path.join(ROOT, "tests", "fixtures", "positions.json")

POSITIONS_PER_TABLE = 120        # at each of two, three and four players


def _write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(text)
    print(f"  {os.path.relpath(path, ROOT)}  {os.path.getsize(path) / 1024:.0f} kB")


def _write_json(path, payload):
    _write(path, json.dumps(payload, separators=(",", ":")) + "\n")


def export_policy(checkpoint):
    with open(checkpoint) as fh:
        d = json.load(fh)
    body = {
        "generation": d.get("generation"),
        "hidden": d["hidden"],
        "trainedAtPlayers": d.get("n_players"),
        "features": FEATURE_NAMES,
        "actions": ACTION_NAMES,
        "theta": d["theta"],
    }
    _write(POLICY_OUT,
           "// Generated by ml/export_web.py from ml/runs/duel.json.\n"
           "// The trained ship's weights. Do not edit by hand -- retrain and\n"
           "// re-export instead. `features` and `actions` record the orders\n"
           "// these weights were fitted against; policies.ts checks them.\n"
           "const policy = "
           + json.dumps(body, separators=(",", ":"))
           + " as const;\n\nexport default policy;\n")
    return d


def collect_positions(policy, per_table, seed=7):
    """Walk real games and photograph the position before a decision.

    Sampled across two to four players and across the whole arc of a game, so
    the fixtures cover openings, disarm situations and the ragged endgame where
    the deck has run dry -- not just the tidy middle. One position per step, so
    the samples spread over game time rather than clustering in whichever batch
    row happens to run longest.
    """
    rng = np.random.default_rng(seed)
    heuristic = HeuristicPolicy()
    greedy = GreedyPolicy()
    out = []

    for n_players in (2, 3, 4):
        taken = 0
        env = Spaceships(48, n_players, rng=np.random.default_rng(seed + n_players))
        while taken < per_table:
            rows = env.active
            if not len(rows):                     # batch played out; deal again
                env.reset()
                env.done[:] = False
                continue
            targets = env.choose_targets(rows)
            obs = env.features(rows, targets)
            legal = env.legal_actions(rows, targets)
            view = env.public_view(rows, targets)
            scores = policy.scores(obs)

            i = int(rng.integers(len(rows)))
            r = int(rows[i])
            taken += 1
            out.append({
                "nPlayers": n_players,
                "health": env.health[r].tolist(),
                "shield": env.shield[r].tolist(),
                "alive": env.alive[r].tolist(),
                "charges": env.charges[r].tolist(),
                "deck": env.deck[r].tolist(),
                "discard": env.discard[r].tolist(),
                "cur": int(env.cur[r]),
                "turns": int(env.turns[r]),
                "expect": {
                    "target": int(targets[i]),
                    "legal": [bool(x) for x in legal[i]],
                    "features": [float(x) for x in obs[i]],
                    "mlpScores": [float(x) for x in scores[i]],
                    "mlp": int(policy.act(obs[i:i + 1], legal[i:i + 1],
                                          {k: v[i:i + 1] for k, v in view.items()},
                                          rng)[0]),
                    "heuristic": int(heuristic.act(obs[i:i + 1], legal[i:i + 1],
                                                   {k: v[i:i + 1] for k, v in view.items()},
                                                   rng)[0]),
                    "greedy": int(greedy.act(obs[i:i + 1], legal[i:i + 1],
                                             {k: v[i:i + 1] for k, v in view.items()},
                                             rng)[0]),
                },
            })

            actions = heuristic.act(obs, legal, view, rng, rows)
            # Half the tables play the trained policy instead, so the fixtures
            # see positions both styles of play actually reach.
            mixed = rng.random(len(rows)) < 0.5
            if mixed.any():
                sel = np.flatnonzero(mixed)
                actions[sel] = policy.act(obs[sel], legal[sel],
                                          {k: v[sel] for k, v in view.items()},
                                          rng, rows[sel])
            env.step(rows, actions, targets)

    return out


def main():
    print("exporting the trained ship to the web app")
    d = export_policy(CHECKPOINT)
    policy = MLPPolicy(np.array(d["theta"]), hidden=d["hidden"], temperature=0.0)
    positions = collect_positions(policy, POSITIONS_PER_TABLE)
    _write_json(FIXTURE_OUT, {
        "note": "generated by ml/export_web.py -- do not edit by hand",
        "features": FEATURE_NAMES,
        "actions": ACTION_NAMES,
        "nActions": N_ACTIONS,
        "positions": positions,
    })
    print(f"  {len(positions)} positions, "
          f"{sum(p['nPlayers'] == 2 for p in positions)} of them duels")


if __name__ == "__main__":
    main()
